// <auto-generated />
namespace TMDT.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class editColumnContact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editColumnContact));
        
        string IMigrationMetadata.Id
        {
            get { return "201807181551059_editColumnContact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
